### ISSUE TITLE
Maldives: special characters allowed for a person's name

### ISSUE THREAD

**Issue by eryzna** [seasketch/next#263]
No error when special characters (!"#¤%&/()=...) are entered in name field. These characters can therefore be submitted as a person's name.

**Comment by underbluewaters** [comment]
I'm okay with this one. It's hard to anticipate what form a person's name might take due to language differences or just [being a unique person](https://parkerhiggins.net/2013/01/writing-the-prince-symbol-in-unicode/). I believe just collecting a string is best practice since there's no canonical definition of a name.

If we run into unique cases with particular projects we can always add some sort of validation setting. Maybe admins could provide a regex
