### ISSUE TITLE
Evaluate Skip Logic during export to null values for skipped questions

### ISSUE THREAD

**Issue by eryzna** [seasketch/next#268]
Spoke with Maddie about legacy survey issues regarding atoll/island questions occasionally persisting bad data. There is a similar but perhaps unrelated issue I noticed with SeaSketch Next Maldives survey. 

Legacy: some responses downloaded from the survey are showing atoll / island combinations that should be impossible. The atoll question is required, and when a respondent chooses an atoll, the survey then populates a subsequent question asking which island in that atoll they reside on, which is also required. The choices for this second question are only islands that pertain to the atoll chosen. However, I am seeing responses where the island reported is not one of the islands that exists in the atoll reported.

SeaSketch Next: atoll question is required, but by user selecting atoll and then returning to atoll question via survey arrows, user can deselect atoll and proceed to next question via survey arrows without making atoll selection (see attached). The atoll islands dropdown then seems to populate with default "HA" atoll. I wonder what the data looks like after response submission, and if it is related to Maddie's issue.

**Comment by underbluewaters** [comment]
The survey logic in legacy SeaSketch just controls visibility of fields. Same goes for SeaSketch Next where the "skip logic" informs navigation. It would be pretty tricky to cover all these corner cases. Though, I'm noticing on the SeaSketch Next version of the Maldives survey those island questions are marked as not required. Making them required may solve this. Not entirely sure.

**Comment by underbluewaters** [comment]
Okay, setting these required does "solve" the issue in that users can't skip the question. If a user changes atolls however, they will still have their previous island selection. So they may have this type of data in the export:

atoll | island_HA | island_AA | island_B | etc...
---------------------------------------------
AA   | isle_z         | isle_j         | null         | null

At this point it would be up to the downstream data processing scripts to handle these conflicts. The way to avoid that would be to evaluate the navigation path through the survey at time of export and null those questions that would be skipped. This seems like a great addition but probably won't appear in v1.

Pinging @madelinemberger since this would probably most effect her.
