### ISSUE TITLE
Basemap Error when trying to add from existing project basemaps

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#441]
I'm trying to add an existing project map (recfish_flores) to a new survey (Phase 1 Heatmaps Outreach, https://next.seasket.ch/blueazores/admin/surveys/157). Using the tool to "select from project maps", and pointing to recfish_flores, I get an error:

Basemap Error: Content at mapbox://styles/seasketch/cl0ee8b80001i15ruq1fsuozo does not appear to be a Mapbox GL Style

<img width="1657" alt="Screenshot 2022-11-03 at 11 24 14 AM" src="https://user-images.githubusercontent.com/932832/199804612-a43aec5d-065c-4ae0-bbdc-7d24ded3ecac.png">

If I add the same basemap by choosing "new basemap" pointing to the Mapbox URL (mapbox://styles/seasketch/cl0j2qxus000i15qwcrxyhlka), I'm able to add it but I have trouble editing the name. Basically, I'm only able to enter one letter for the name, pause 5 seconds, enter one more, pause 5 seconds. 

<img width="1680" alt="Screenshot 2022-11-03 at 11 18 08 AM" src="https://user-images.githubusercontent.com/932832/199805212-ba6ce196-0457-4530-9a42-f1565334dd81.png">

We need to get this working for early next week, if at all possible.

**Comment by underbluewaters** [comment]
There are a couple things going on here. It looks like the existing basemap you found in the project pointed to a map in our account that has since been deleted. Because another survey somewhere is pointing to it, it doesn't show the "discard" option.

For renaming a new basemap, the fix for this would be to copy and paste the full name you want for now until I can fix that text field.

Closing this ticket in favor of two separate linked issues.
