### ISSUE TITLE
Collection reports don't always update when new sketches are added in FSM project

### ISSUE THREAD

**Issue by wmcclin** [seasketch/next#539]
This needs more testing but this morning I created a network with 5 shapes, ran a report, then added another shape and re-ran the report. The size report didn't appear to update with the additional shape. I then changed the name of the collection (adding "v2) and the size report updated. 
<img width="1552" alt="Screenshot 2023-01-25 at 12 03 21 PM" src="https://user-images.githubusercontent.com/932832/214456558-a52a33c9-efe4-4627-bb75-63a1c7193026.png">

Collection added to Admin forum.

**Comment by underbluewaters** [comment]
This is a tricky one. SeaSketch needs to send an accurate updatedAt date when requesting new reports so that the stale caches are avoided. This means keeping the collection metadata up to date when child sketches are modified. I've handled this correctly when a user edits a sketch that is part of a collection, but there are a whole lot of other cases to handle.

- [ ] sketch is added to a collection
- [ ] sketch is removed from a collection
- [ ] child sketch is deleted
- [ ] + these same cases but for child folders that contain sketches

That's a lot to cover. Working on this now.
